### ISSUE TITLE
gradle clean build 失败了

### ISSUE THREAD

**Issue by JustUse** [Tencent/bk-ci#1286]
> Task :core:process:api-process:check
Skipping task ':core:process:api-process:check' as it has no actions.
:core:process:api-process:check (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.0 secs.
:core:process:api-process:build (Thread[Task worker for ':' Thread 2,5,main]) started.

> Task :core:process:api-process:build
Skipping task ':core:process:api-process:build' as it has no actions.
:core:process:api-process:build (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.0 secs.
:core:process:biz-process:assemble (Thread[Task worker for ':' Thread 2,5,main]) started.

> Task :core:process:biz-process:assemble
Skipping task ':core:process:biz-process:assemble' as it has no actions.
:core:process:biz-process:assemble (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.0 secs.
:core:process:biz-process:compileTestKotlin (Thread[Task worker for ':' Thread 2,5,main]) started.
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.2.10/85fe1811f3e586d0cc53aba1394d8089f1862215/kotlin-stdlib-jdk8-1.2.10.jar (version 1.2)
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.3.10/dd02865be0351707554b16a896b766b2396cdafa/kotlin-reflect-1.3.10.jar (version 1.3)
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.2.10/cfe8b616b3bf0811ef70863c86b745a2e767a66e/kotlin-stdlib-jdk7-1.2.10.jar (version 1.2)
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.10/b178c1501609c6e4ee8be635513cb023a466457d/kotlin-stdlib-1.3.10.jar (version 1.3)
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.10/1b19d99229dcedad7caf50534dce38fe82845269/kotlin-stdlib-common-1.3.10.jar (version 1.3)
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.2.71/d5439926359caa899f41e1915b19d6d23e49750b/kotlin-script-runtime-1.2.71.jar (version 1.2)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
e: /root/bk-ci/src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/service/BuildVariableServiceTest.kt: (51, 9): Cannot find a parameter with this name: dslContext
e: /root/bk-ci/src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/service/BuildVariableServiceTest.kt: (53, 5): No value passed for parameter 'commonDslContext'

> Task :core:process:biz-process:compileTestKotlin FAILED
Task ':core:process:biz-process:compileTestKotlin' is not up-to-date because:
  Task.upToDateWhen is false.
All input files are considered out-of-date for incremental task ':core:process:biz-process:compileTestKotlin'.
file or directory '/root/bk-ci/src/backend/ci/core/process/biz-process/src/test/java', not found
file or directory '/root/bk-ci/src/backend/ci/core/process/biz-process/src/test/java', not found
Using Kotlin incremental compilation
[KOTLIN] deleting /root/bk-ci/src/backend/ci/core/process/biz-process/build/classes/kotlin/test on error
[KOTLIN] deleting /root/bk-ci/src/backend/ci/core/process/biz-process/build/classes/kotlin/test on error
:core:process:biz-process:compileTestKotlin (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.726 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:process:biz-process:compileTestKotlin'.
> Compilation error. See log for more details

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core:process:biz-process:compileTestKotlin'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Compilation error. See log for more details
        at org.jetbrains.kotlin.gradle.tasks.TasksUtilsKt.throwGradleExceptionIfError(tasksUtils.kt:8)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.processCompilerExitCode(Tasks.kt:374)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:348)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:242)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:214)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 58s
430 actionable tasks: 430 executed

**Comment by zanyzhao** [comment]
你的gradle版本是？

**Comment by JustUse** [comment]
> 你的gradle版本是？

[root@localhost ci]# gradle --version

------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
OS:           Linux 3.10.0-1127.el7.x86_64 amd64

**Comment by JustUse** [comment]
> 你的gradle版本是？

而且应该是 cd bk-ci/src/backend/ci & gradle clean build  不是source_compile.md写的cd bk-ci/src/backend & gradle clean build

**Comment by zanyzhao** [comment]
看到了，我fix一下

**Comment by JustUse** [comment]
> 看到了，我fix一下

gradle clean build 失败的原因找到了吗？

**Comment by JustUse** [comment]
> 你的gradle版本是？

或者是哪里的原因导致的，我希望能尽快解决这个问题

**Comment by zanyzhao** [comment]
如果你想在本地完成编译，可以参考下我这个Action workflow
https://github.com/Tencent/bk-ci/actions/runs/94359604/workflow

**Comment by JustUse** [comment]
> 如果你想在本地完成编译，可以参考下我这个Action workflow
> https://github.com/Tencent/bk-ci/actions/runs/94359604/workflow

我换了和你们那个一样的gradle 4.8.1版本；还是报一样的错
e: /root/bk-ci/src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/service/BuildVariableServiceTest.kt: (51, 9): Cannot find a parameter with this name: dslContext
e: /root/bk-ci/src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/service/BuildVariableServiceTest.kt: (53, 5): No value passed for parameter 'commonDslContext'

**Comment by JustUse** [comment]
> 如果你想在本地完成编译，可以参考下我这个Action workflow
> https://github.com/Tencent/bk-ci/actions/runs/94359604/workflow

是不是要证书什么的？这个基本上是最后一步了

信息: Generating table         : TCert.java [input=t_cert, output=t_cert, pk=KEY_t_cert_PRIMARY]
五月 06, 2020 5:27:24 下午 org.jooq.tools.JooqLogger info
信息: Generating table         : TCertEnterprise.java [input=t_cert_enterprise, output=t_cert_enterprise, pk=KEY_t_cert_enterprise_PRIMARY]
五月 06, 2020 5:27:24 下午 org.jooq.tools.JooqLogger info
信息: Generating table         : TCertTls.java [input=t_cert_tls, output=t_cert_tls, pk=KEY_t_cert_tls_PRIMARY]
五月 06, 2020 5:27:24 下午 org.jooq.tools.JooqLogger info
信息: Generating table         : TCredential.java [input=t_credential, output=t_credential, pk=KEY_t_credential_PRIMARY]

**Comment by JustUse** [comment]
> 如果你想在本地完成编译，可以参考下我这个Action workflow
> https://github.com/Tencent/bk-ci/actions/runs/94359604/workflow

更新了代码，重新导入数据库脚本后端编译终于通过了，太难了 - -

**Comment by JustUse** [comment]
> 如果你想在本地完成编译，可以参考下我这个Action workflow
> https://github.com/Tencent/bk-ci/actions/runs/94359604/workflow

你可以加我一下qq吗？1358825456   我发现bk-ci 网关部署文档有问题，老是在github提问题太麻烦了

**Comment by JustUse** [comment]
> 如果你想在本地完成编译，可以参考下我这个Action workflow
> https://github.com/Tencent/bk-ci/actions/runs/94359604/workflow

你们还是整理一下"一分钟安装部署"这个文档吧，感觉和现在的版本很多都对不上了 : (

**Comment by zanyzhao** [comment]
> > 如果你想在本地完成编译，可以参考下我这个Action workflow
> > https://github.com/Tencent/bk-ci/actions/runs/94359604/workflow
> 
> 你们还是整理一下"一分钟安装部署"这个文档吧，感觉和现在的版本很多都对不上了 : (

确实，我更新下部署文档，感谢反馈
