### ISSUE TITLE
Frontend构建失败

### ISSUE THREAD

**Issue by wwyhy** [Tencent/bk-ci#179]
Hi，

根据下面的前端构建指令(centos 7)，yarn public 指令构建失败。
https://github.com/Tencent/bk-ci/blob/master/docs/install/frontend.md. 

```
[root@proxy frontend]# yarn public
yarn run v1.19.1
$ gulp -d frontend
[06:10:59] Using gulpfile ~/bk-ci/src/frontend/gulpfile.js
[06:10:59] Starting 'default'...
[06:10:59] Starting 'copy'...
[06:10:59] Starting 'build'...
⠹ building bk-ci frontend project[06:11:00] Finished 'copy' after 300 ms
⠧ building bk-ci frontend project{ Error: Command failed: yarn build -- -- --env.dist=frontend
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
lerna notice cli v3.18.3
lerna info versioning independent
lerna info Executing command in 6 packages: "yarn run public:external --env.dist=frontend"
devops-pipeline: warning package.json: No license field
devops-pipeline: npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1572934268198-0.6695144255224679/node but npm is using /data/node8/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
devops-nav: npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1572934267668-0.5228430402522217/node but npm is using /data/node8/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
devops-nav: npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1572934267668-0.5228430402522217/node but npm is using /data/node8/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
devops-pipeline: npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1572934268198-0.6695144255224679/node but npm is using /data/node8/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
devops-codelib: error Command failed with exit code 1.
lerna ERR! yarn run public:external --env.dist=frontend exited 1 in 'devops-codelib'
lerna ERR! yarn run public:external --env.dist=frontend stdout:
$ cross-env NODE_ENV=external webpack --mode production --env.dist=frontend
aaadddsd { dist: 'frontend' }
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run public:external --env.dist=frontend stderr:
error Command failed with exit code 1.

lerna ERR! yarn run public:external --env.dist=frontend exited 1 in 'devops-codelib'
lerna WARN complete Waiting for 5 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn build -- -- --env.dist=frontend' }
[06:12:02] The following tasks did not complete: default, build
[06:12:02] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

请问下这个是什么问题呢

**Comment by Roy9102** [comment]
@wwyhy 你的yarn版本和node版本分别是什么？

**Comment by wwyhy** [comment]
node: v8.16.2
npm: 6.4.1
yarn: 1.19.1

node10.12这个版本也试过，同样报错
