### ISSUE TITLE
添加构建节点失败

### ISSUE THREAD

**Issue by SPARON** [Tencent/bk-ci#2035]
bk-ci是使用的docker镜像： https://hub.docker.com/r/blueking/bk-ci

1. docker方式启动bk-ci
2. 创建Centos8虚拟机
3. Web界面添加节点，复制添加节点命令
4. 在新建的虚拟机执行添加操作
5. 点击添加节点对话框的“暂未连接任何节点，点击刷新”按钮链接节点
6. 点击【导入】按钮
7. 系统报错：For input string: "machine"

查看日志：
`
2020.07.09 09:05:32,794 [IO-2 task-48]  INFO c.t.d.e.s.t.ThirdPartyAgentMgrService    695  Trying to import the agent(koapydmd) of project(demo) by user(admin)
2020.07.09 09:05:32,839 [IO-2 task-48] ERROR t.d.c.w.h.IllegalArgumentExceptionMapper 49   Failed with illegal argument exception
java.lang.NumberFormatException: For input string: "machine"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.tencent.devops.environment.service.thirdPartyAgent.ThirdPartyAgentMgrService$importAgent$1.run(ThirdPartyAgentMgrService.kt:723)
        at org.jooq.impl.DefaultDSLContext$3.run(DefaultDSLContext.java:521)
        at org.jooq.impl.DefaultDSLContext$3.run(DefaultDSLContext.java:518)
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:464)
        at org.jooq.impl.Tools$10$1.block(Tools.java:3405)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at org.jooq.impl.Tools$10.get(Tools.java:3402)
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:501)
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:434)
        at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:518)
        at com.tencent.devops.environment.service.thirdPartyAgent.ThirdPartyAgentMgrService.importAgent(ThirdPartyAgentMgrService.kt:696)
        at com.tencent.devops.environment.resources.thirdPartyAgent.UserThirdPartyAgentResourceImpl.importAgent(UserThirdPartyAgentResourceImpl.kt:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
`

**Comment by irwinsun** [comment]
这个是属于初始化数据问题导致，
需要删除原来devops_ci_environment 数据库中的旧数据
delete from devops_ci_environment.T_ENVIRONMENT_THIRDPARTY_AGENT where NODE_ID = 1;
delete from devops_ci_environment.T_NODE where NODE_ID = 1;
