### ISSUE TITLE
project启动失败

### ISSUE THREAD

**Issue by asonke** [Tencent/bk-ci#2577]
2020-09-15 14:12:59.116  INFO 17466 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2020-09-15 14:12:59.612  WARN 17466 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/project$%7Bservice-suffix%7D/default": 拒绝连接 (Connection refused); nested exception is java.net.ConnectException: 拒绝连接 (Connection refused)
2020-09-15 14:12:59.635 ERROR 17466 --- [           main] o.s.b.SpringApplication                  : Application startup failed

java.lang.RuntimeException: java.lang.IllegalArgumentException: Could not resolve placeholder 'service-suffix' in value "project${service-suffix}"
        at com.tencent.devops.common.service.Log4j2Initializer.initialize(Log4j2Initializer.java:77) ~[common-service-1.1.7-RELEASE.jar!/:?]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567) [spring-boot-1.5.11.RELEASE.jar!/:1.5.11.RELEASE]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338) [spring-boot-1.5.11.RELEASE.jar!/:1.5.11.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) [spring-boot-1.5.11.RELEASE.jar!/:1.5.11.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.11.RELEASE.jar!/:1.5.11.RELEASE]
        at com.tencent.devops.common.service.MicroServiceApplication.run(MicroServiceApplication.kt:38) [common-service-1.1.7-RELEASE.jar!/:?]
        at com.tencent.devops.project.ApplicationKt.main(Application.kt:38) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [boot-project.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [boot-project.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [boot-project.jar:?]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [boot-project.jar:?]
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'service-suffix' in value "project${service-suffix}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174) ~[spring-core-4.3.15.RELEASE.jar!/:4.3.15.RELEASE]
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126) ~[spring-core-4.3.15.RELEASE.jar!/:4.3.15.RELEASE]
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:236) ~[spring-core-4.3.15.RELEASE.jar!/:4.3.15.RELEASE]

**Comment by irwinsun** [comment]
>2020-09-15 14:12:59.116 INFO 17466 --- [ main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2020-09-15 14:12:59.612 WARN 17466 --- [ main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/project$%7Bservice-suffix%7D/default": 拒绝连接 (Connection refused); nested exception is java.net.ConnectException: 拒绝连接 (Connection refused)

这个是正常的，因为默认启用了spring config server ，如果没有配置server地址，会自动去连接本地8888端口，失败了也不影响。

但是
>2020-09-15 14:12:59.635 ERROR 17466 --- [ main] o.s.b.SpringApplication : Application startup failed
java.lang.RuntimeException: java.lang.IllegalArgumentException: Could not resolve placeholder 'service-suffix' in value "project${service-suffix}"

这个应该是启动时没有按要求，可以参考下support-files/templates/#etc#ci#common.yml 配置是有这个配置项

不知道你是怎么操作的？

**Comment by asonke** [comment]
./render_tpl -m ci ../support-files/templates/*
直接执行的这一步.
我的common里面我看这个配置项也改成了 
service-suffix: "-ci"
# http concurrency
server:
  undertow:
    worker-threads: 100

**Comment by asonke** [comment]
[common.txt](https://github.com/Tencent/bk-ci/files/5224088/common.txt)
这个我的common.yml的文件

**Comment by asonke** [comment]
我的这个机器上还装了bkce,   consul,es这些中间件能共用bkce的吗?   会不会有冲突的一些问题.

**Comment by irwinsun** [comment]
> [common.txt](https://github.com/Tencent/bk-ci/files/5224088/common.txt)
> 这个我的common.yml的文件

你的包是自己编译的吗？ 一个正常编译出来的包，包含了boot-project.jar以及boot-project.sh(启动命令）
可以看看我们出的[https://github.com/Tencent/bk-ci/releases](https://github.com/Tencent/bk-ci/releases)

配置文件没问题的话，那就跟启动有关了，启动命令中指定了配置文件路径，
![image](https://user-images.githubusercontent.com/16686129/93197202-f153e000-f77d-11ea-8edb-75d4e4e170d7.png)

所有的微服务的启动命令都是从[boot-service.sh](https://github.com/Tencent/bk-ci/blob/master/support-files/templates/boot-service.sh) 这个文件转换而来的

**Comment by asonke** [comment]
我按照文档编译出来的, 编译2次了..
![image](https://user-images.githubusercontent.com/71312959/93197657-80f98e80-f77e-11ea-87a1-f713e6623270.png)

**Comment by irwinsun** [comment]
1. 你部署在哪个目录呢，
2. 方便展示下这个目录下的 etc/ci子目录， ci子目录

**Comment by asonke** [comment]
/data/bkee/

![image](https://user-images.githubusercontent.com/71312959/93198009-f8c7b900-f77e-11ea-87a2-fdcdcf040caa.png)

**Comment by irwinsun** [comment]
/data/bkee/ci/project 目录呢

**Comment by asonke** [comment]
![image](https://user-images.githubusercontent.com/71312959/93198916-3711a800-f780-11ea-8b52-57818a71f12f.png)

**Comment by asonke** [comment]
我下载了https://github.com/Tencent/bk-ci/releases/download/v1.2.0-alpha.8/bkci.tar.gz   用你们这个编译好的文件重新启动还是一样的报错, 问题应该出在配置文件上, 我看脚本里面的指向配置文件也没有错...

**Comment by irwinsun** [comment]
其他服务正常么 是用boot-project.sh 还是 project.sh （你自己写的？）启动的

先选择  sh boot-project.sh start &  ps -ef | grep "boot-project.jar"  看下启动参数

**Comment by asonke** [comment]
用你们提供的boot-project.sh的脚本 改了个名字  其他服务也起不来.  
![image](https://user-images.githubusercontent.com/71312959/93287932-54d91e80-f80d-11ea-8ad0-28caf5772328.png)

**Comment by asonke** [comment]
![image](https://user-images.githubusercontent.com/71312959/93288002-7cc88200-f80d-11ea-8c1a-6ece8e0eb3db.png)

**Comment by irwinsun** [comment]
进程展示的读取配置文件路径是/data/bkce/etc/ci
但你的环境实际配置文件路径是 /data/bkee/etc/ci

是不是你本地渲染模板配置的bkenv.properties
INSTALL_PATH 配置项配置错了

**Comment by asonke** [comment]
我的这台机器上也安装了bkce,   默认读取的路径是bkce.....
![image](https://user-images.githubusercontent.com/71312959/93288531-97e7c180-f80e-11ea-896f-6b4ab8f947d0.png)
知道问题出在哪里了

**Comment by asonke** [comment]
我蓝鲸平台跟bk-ci装在一台机器上导致这个变量读取是蓝鲸的路径.

**Comment by asonke** [comment]
![image](https://user-images.githubusercontent.com/71312959/93289190-640d9b80-f810-11ea-9090-21cc36de4c88.png)
![image](https://user-images.githubusercontent.com/71312959/93289201-6ec83080-f810-11ea-91d8-77dd5ae95bd5.png)
读取BK_HOME的这段我已经修改了,  没有那段报错了  但是服务还是起不来, 到拒绝连接这里就没有日志了.

**Comment by irwinsun** [comment]
这个是打屏的console日志，有这个日志是因为在boot-project.sh中打开了NOHUPLOG配置。正常日志都会输出在  /data/bkee/logs/ci/project/目录下

**Comment by sunshinejdq** [comment]
> 这个是打屏的console日志，有这个日志是因为在boot-project.sh中打开了NOHUPLOG配置。正常日志都会输出在 /data/bkee/logs/ci/project/目录下
> 
> 关于连接拒绝这个问题只会出现打屏日志影响，但不影响启动。如想关掉，可以在启动脚本boot-xxx.sh中的JAVA_OPSTS启动参数加上 -Dspring.cloud.config.enabled=false
> 也可以在部署机器上设置环境变量
> export SPRING_CLOUD_CONFIG_ENABLED=false
嗯，我已经查到了，是rabbitmq的问题，多谢
