### ISSUE TITLE
后端微服务启动rabbitmq报错

### ISSUE THREAD

**Issue by sunshinejdq** [Tencent/bk-ci#2624]
`Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'q.engine.pipeline.bl.agent.dispatch.startup' in vhost 'ci', class-id=50, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:505)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:336)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:143)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:90)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:634)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:572)
`
[root@VM-16-65-centos dispatch]# rabbitmqctl list_vhosts
Listing vhosts ...
name
ci
[root@VM-16-65-centos dispatch]# rabbitmqctl list_users
Listing users ...
user	tags
guest1	[administrator]
//comm.yml
# rabbitmq config
  rabbitmq:
    # 引擎核心业务MQ
    core:
      virtual-host: ci
      username: guest1
      password: guest1
      addresses: 127.0.0.1:5672

**Comment by irwinsun** [comment]
该队列会在 dispatch微服务启动时自动创建。 请问你这个是从个分支码获取编译的？
可以使用我们最新的版本来安装
https://github.com/Tencent/bk-ci/releases/tag/v1.2.0
对应源码分支是 https://github.com/Tencent/bk-ci/tree/v1.2.0
