### ISSUE TITLE
run   java -jar  boot-assembly.jar  -Dspring.cloud.config.fail-fast=True  fail 

### ISSUE THREAD

**Issue by mikeeastin** [Tencent/bk-ci#6147]
[root@jszx-test release]# java -jar  boot-assembly.jar  -Dspring.cloud.config.fail-fast=True
2022-02-15 15:18:00.791|||EnableEncryptablePropertiesBeanFactoryPostProcessor.java|39|INFO||||||[main] Post-processing PropertySource instances
2022-02-15 15:18:00.906|||EncryptablePropertySourceConverter.java|56|INFO||||||[main] Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy
2022-02-15 15:18:00.907|||EncryptablePropertySourceConverter.java|56|INFO||||||[main] Converting PropertySource bootstrap [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2022-02-15 15:18:00.907|||EncryptablePropertySourceConverter.java|56|INFO||||||[main] Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2022-02-15 15:18:00.907|||EncryptablePropertySourceConverter.java|56|INFO||||||[main] Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2022-02-15 15:18:00.908|||EncryptablePropertySourceConverter.java|56|INFO||||||[main] Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper
2022-02-15 15:18:00.909|||EncryptablePropertySourceConverter.java|56|INFO||||||[main] Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2022-02-15 15:18:00.909|||EncryptablePropertySourceConverter.java|56|INFO||||||[main] Converting PropertySource cachedrandom [org.springframework.cloud.util.random.CachedRandomPropertySource] to EncryptablePropertySourceWrapper
2022-02-15 15:18:00.909|||EncryptablePropertySourceConverter.java|56|INFO||||||[main] Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2022-02-15 15:18:01.208|||PostProcessorRegistrationDelegate.java|376|INFO||||||[main] Bean 'org.springframework.retry.annotation.RetryConfiguration' of type [org.springframework.retry.annotation.RetryConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-02-15 15:18:01.278|||DefaultLazyPropertyFilter.java|31|INFO||||||[main] Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
2022-02-15 15:18:03.473  INFO 21665 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-config/application/'}]
2022-02-15 15:18:03.583 ERROR 21665 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'configServerRetryInterceptor' that could not be found.

Action:

Consider defining a bean named 'configServerRetryInterceptor' in your configuration.

**Comment by mikeeastin** [comment]
search  file  bk-ci\src\backend\ci\boot-assembly\src\main\resources\application.yml
add property    spring.cloud.config.failFast=true   ,also  not work 

---------------
2022-02-15 15:56:05.518 ERROR 23733 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************
Description:
A component required a bean named 'configServerRetryInterceptor' that could not be found.
Action:

Consider defining a bean named 'configServerRetryInterceptor' in your configuration.

**Comment by mikeeastin** [comment]
code   branch  release-1.8 , https://github.com/Tencent/bk-ci/tree/release-1.8

**Comment by mikeeastin** [comment]
[root@jszx-test release]# /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.322.b06-1.el7_9.x86_64/bin/java  -Xms2g -Xmx2g -XX:NewRatio=1 -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC -server -Dcertificate.file=/data/bkee-0216/cert/bkci_platform.cert -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dspring.config.location=file:/data/bkee-0216/etc/ci/common.yml,file:/data/bkee-0216/etc/ci/application-assembly.yml -Dservice.log.dir=/data/bkee-0216/logs/ci/assembly/ -Dspring.cloud.config.uri=http://10.11.10.116:8500 -Dspring.cloud.config.failFast=true -Dspring.cloud.consul.config.enabled=true -Ddevops_gateway=http://devops.bktencent.com -classpath /data/bkee-0216/ci/boot-assembly/config:. -jar /data/bkee-0216/ci/boot-assembly/boot-assembly.jar
maxFileSize:300 MB,maxFileAge:30d,maxFileIndex:30
2022-02-17 10:56:25.239  INFO 9172 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-config/application/'}]
2022-02-17 10:56:25.411  INFO 9172 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://10.11.10.116:8500
2022-02-17 10:56:26.767  INFO 9172 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://10.11.10.116:8500
2022-02-17 10:56:27.992  INFO 9172 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://10.11.10.116:8500
2022-02-17 10:56:29.308  INFO 9172 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://10.11.10.116:8500
2022-02-17 10:56:30.752  INFO 9172 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://10.11.10.116:8500
2022-02-17 10:56:32.372  INFO 9172 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://10.11.10.116:8500
2022-02-17 10:56:32.495 ERROR 9172 --- [           main] o.s.b.SpringApplication                  : Application run failed

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing: None of labels [] found
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:133) ~[spring-cloud-config-client-3.0.3.jar!/:3.0.3]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) ~[spring-cloud-context-3.0.2.jar!/:3.0.2]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locateCollection(ConfigServicePropertySourceLocator.java:145) ~[spring-cloud-config-client-3.0.3.jar!/:3.0.3]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invoke(<generated>) ~[spring-cloud-config-client-3.0.3.jar!/:3.0.3]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.6.jar!/:5.3.6]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:93) ~[spring-retry-1.3.1.jar!/:?]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-1.3.1.jar!/:?]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209) ~[spring-retry-1.3.1.jar!/:?]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:119) ~[spring-retry-1.3.1.jar!/:?]
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:163) ~[spring-retry-1.3.1.jar!/:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$df917767.locateCollection(<generated>) ~[spring-cloud-config-client-3.0.3.jar!/:3.0.3]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) ~[spring-cloud-context-3.0.2.jar!/:3.0.2]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:650) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:403) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144) [spring-boot-2.4.5.jar!/:2.4.5]
	at com.tencent.devops.common.service.MicroServiceApplication.run(MicroServiceApplication.kt:40) [common-service-1.7.0-RELEASE.jar!/:?]
	at com.tencent.devops.AssemblyApplicationKt.main(AssemblyApplication.kt:56) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_322]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_322]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_322]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_322]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [boot-assembly.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [boot-assembly.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [boot-assembly.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [boot-assembly.jar:?]
