### ISSUE TITLE
前端编译时出错yarn public 

### ISSUE THREAD

**Issue by net2817** [Tencent/bk-ci#934]
[root@bk-ci-172-16-10-207 frontend]# yarn public 
yarn run v1.22.4
$ gulp -d frontend
[18:09:14] Using gulpfile /data/bk-ci/src/frontend/gulpfile.js
[18:09:14] Starting 'default'...
[18:09:14] Starting 'devops'...
[18:09:14] Starting 'pipeline'...
[18:09:14] Starting 'copy'...
[18:09:14] Starting 'build'...
[18:09:14] Starting '<anonymous>'...
[18:09:14] Starting '<anonymous>'...
⠦ building bk-ci frontend project[18:09:15] Finished 'copy' after 745 ms
⠇ building bk-ci frontend projectError: Command failed: lerna run public:master --scope=devops-undefined -- --env.dist=frontend --env.lsVersion=dev
lerna notice cli v3.17.0
lerna info versioning independent
lerna info filter [ 'devops-undefined' ]
lerna ERR! EFILTER No packages remain after filtering [ 'devops-undefined' ]

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:505:15)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'lerna run public:master --scope=devops-undefined -- --env.dist=frontend --env.lsVersion=dev'
}
[18:09:15] The following tasks did not complete: default, devops, pipeline, build, <anonymous>, <anonymous>
[18:09:15] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

采用  yarn public -s nav  可以成功。但只能编译devops后面的。
node 12.16.1
npm 6.13.4
yarn 1.22.4

**Comment by tuntuntutu** [comment]
啥时候能解决呀

**Comment by lockiechen** [comment]
@tuntuntutu 已经修复了哈

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by mikeeastin** [comment]
1. 当前蓝鲸社区版产品和版本【必填】： bk-ci    release1.8 ，操作系统 虚拟机  centos  7 , 后面换了一台配置较好的，就没报错了
2. 报错截图【必填】： 如下 3 报错异常日志

3. 异常相关的日志详情【必填】：

⠴ building bk-ci frontend projectError: Command failed: lerna run public:master  -- --env dist=frontend --env lsVersion=dev
lerna notice cli v3.17.0
lerna info versioning independent
lerna info Executing command in 9 packages: "yarn run public:master --env dist=frontend --env lsVersion=dev"
lerna info run Ran npm script 'public:master' in 'devops-artifactory' in 120.5s:
lerna ERR! yarn run public:master --env dist=frontend --env lsVersion=dev exited 1 in 'devops-atomstore'
lerna ERR! yarn run public:master --env dist=frontend --env lsVersion=dev stdout:
$ cross-env NODE_ENV=master webpack --mode production --env dist=frontend --env lsVersion=dev
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run public:master --env dist=frontend --env lsVersion=dev stderr:
warning package.json: No license field
error Command failed with exit code 1.

lerna ERR! yarn run public:master --env dist=frontend --env lsVersion=dev exited 1 in 'devops-atomstore'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:537:15)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'lerna run public:master  -- --env dist=frontend --env lsVersion=dev'
}

4. 报错之前有做过什么特殊操作【选填】： 执行  yarn  public 后失败，报错
5. 为解决异常尝试作过的操作步骤【选填】： 查看了问题https://github.com/Tencent/bk-ci/issues/934
